# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c446e01e861eab5e2a3e8f34f4768977fea8ca6968cfda4633d7b8e211a4302729e15fb50004e701c8b118e795af0e2a0a2ea9debcccb8ebdae6088fa389a4aa

test:
  secret_key_base: 373a039327bb1dfb6e435ac5771b53b396dd16c849de9aab28609f9aceba4e3c28914fc05580c75ab736388b309eba1615a8daa4988d40b0267c182b4ae64aa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
